services:
#    auth.example:
#        class: AuthBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    auth.admin_form_login_authenticator:
      class: AuthBundle\Security\AdminFormLoginAuthenticator
      arguments: ["@router", "@security.password_encoder"]

#    auth.guard_listener:
#      class: AuthBundle\EventListener\GuardListener
#      arguments: ["@router", "@service_container"]
#      tags:
#        - { name: kernel.event_listener, event: kernel.request }


    auth.login_listener:
      class: AuthBundle\EventListener\LoginListener
      arguments: ['@session', '@doctrine.orm.entity_manager']
      tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
