services:
#    auth.example:
#        class: AuthBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    auth.admin_form_login_authenticator:
      class: AuthBundle\Security\AdminFormLoginAuthenticator
      arguments: ["@router", "@security.password_encoder"]
