admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /admin/auth

app:
    resource: '@AppBundle/Controller/'
    type: annotation
