<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmfveh3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmfveh3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMmfveh3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMmfveh3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMmfveh3\appProdProjectContainer(array(
    'container.build_hash' => 'Mmfveh3',
    'container.build_id' => '73af9bfe',
    'container.build_time' => 1547454060,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmfveh3');
