services:
#    system.example:
#        class: SystemBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  twig.extension.session_menu_extension:
    class: SystemBundle\Twig\SessionMenuExtension
    arguments: ["@session","@doctrine.orm.entity_manager"]
    tags:
      - { name: twig.extension }
  system.menu_datafixtures:
    class: SystemBundle\DataFixtures\MenuFixtures
    tags: ['doctrine.fixture.orm']
