<?php
namespace SystemBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{

    // 获取到菜单信息
    public function getMenuByRole($roleId, $nodes, $level = -1)
    {
        if ($level == 0) {
            $list = $this->getEntityManager()
                ->getConnection()
                ->executeQuery('SELECT name,english_name,level,active,node,parent_node,icon FROM menu WHERE status = :status ORDER BY node', [
                'status' => 1
            ])
                ->fetchAll();
        } else {
            $list = $this->getEntityManager()
                ->getConnection()
                ->executeQuery('SELECT name,english_name,level,active,node,parent_node,icon FROM menu WHERE status = :status AND node IN (:ids) ORDER BY node', [
                'status' => 1,
                'ids' => explode(',', $nodes)
            ], [
                'ids' => \Doctrine\DBAL\Connection::PARAM_INT_ARRAY
            ])
                ->fetchAll();
        }
        $menu = [
            'access_list' => [],
            'parent' => [],
            'child' => [],
            'list' => [],
            'node_list' => [],
            'route_node' => [],
            'nav' => []
        ];
        foreach ($list as $val) {
            $menu['access_list'][] = $val['english_name'];
            $routeInfo = [
                'node' => $val['node'],
                'name' => $val['name'],
                'route' => $val['english_name']
            ];
            $menu['route_node'][$val['english_name']] = $routeInfo;
            $parentNode = (intval($val['node']/10000)) * 10000;
            $menu['list'][$parentNode][] = $val['english_name'];
            if ($val['active'] == 1) {
                switch ($val['level']) {
                    case 1:
                        $menu['parent'][] = $val;
                        break;
                    case 2:
                        $menu['child'][$val['parent_node']][] = $val;
                        $menu['node_list'][$val['parent_node']][] = $val['node'];
                        break;
                    case 3:
                        $menu['nav'][$val['parent_node']][] = $val;
                        break;
                    default:
                        break;
                }
            }
        }
        return $menu;
    }


}
