<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKmjuvlq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKmjuvlq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKmjuvlq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKmjuvlq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKmjuvlq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kmjuvlq',
    'container.build_id' => '63a243d6',
    'container.build_time' => 1550891513,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKmjuvlq');
