<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ34akn0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ34akn0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ34akn0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ34akn0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJ34akn0\appDevDebugProjectContainer([
    'container.build_hash' => 'J34akn0',
    'container.build_id' => '49fde24c',
    'container.build_time' => 1550893324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ34akn0');
